import type { NpcDefinition } from '@/types/npc';

/**
 * 20단계 NPC. reactionMs는 목표 반응(ms) — 값이 클수록 NPC가 느려 플레이어에게 유리.
 * 18·19단계는 스토리/해금 연출용 placeholder.
 */
export const NPCS: readonly NpcDefinition[] = [
  {
    id: 1,
    title: '떨보',
    name: '클레이',
    reactionMs: 540,
    tier: 'bronze',
    bossFlag: false,
    unlocked: true,
  },
  {
    id: 2,
    title: '술꾼',
    name: '더그',
    reactionMs: 505,
    tier: 'bronze',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 3,
    title: '농부',
    name: '베티',
    reactionMs: 465,
    tier: 'bronze',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 4,
    title: '허풍쟁이',
    name: '빌리',
    reactionMs: 415,
    tier: 'silver',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 5,
    title: '우편배달부',
    name: '샘',
    reactionMs: 385,
    tier: 'silver',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 6,
    title: '사격선수',
    name: '로사',
    reactionMs: 355,
    tier: 'silver',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 7,
    title: '역마차 강도',
    name: '잭',
    reactionMs: 315,
    tier: 'gold',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 8,
    title: '참전용사',
    name: '콜트',
    reactionMs: 290,
    tier: 'gold',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 9,
    title: '번개손',
    name: '라이더',
    reactionMs: 265,
    tier: 'gold',
    bossFlag: true,
    unlocked: false,
  },
  {
    id: 10,
    title: '독수리눈',
    name: '이글',
    reactionMs: 230,
    tier: 'platinum',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 11,
    title: '서커스',
    name: '데이지',
    reactionMs: 212,
    tier: 'platinum',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 12,
    title: '예언자',
    name: '시빌',
    reactionMs: 195,
    tier: 'platinum',
    bossFlag: true,
    unlocked: false,
  },
  {
    id: 13,
    title: '방울뱀',
    name: '세스',
    reactionMs: 172,
    tier: 'diamond',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 14,
    title: '닥',
    name: '홀리데이',
    reactionMs: 158,
    tier: 'diamond',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 15,
    title: '검은옷',
    name: '레이스',
    reactionMs: 146,
    tier: 'diamond',
    bossFlag: true,
    unlocked: false,
  },
  {
    id: 16,
    title: '죽음의 천사',
    name: '에인절',
    reactionMs: 128,
    tier: 'master',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 17,
    title: '사막의 악마',
    name: '드라이든',
    reactionMs: 118,
    tier: 'master',
    bossFlag: true,
    unlocked: false,
  },
  {
    id: 18,
    title: '???',
    name: '???',
    reactionMs: 108,
    tier: 'legend',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 19,
    title: '???',
    name: '???',
    reactionMs: 102,
    tier: 'legend',
    bossFlag: false,
    unlocked: false,
  },
  {
    id: 20,
    title: '최종 보스',
    name: '흰옷의 사나이',
    reactionMs: 96,
    tier: 'legend',
    bossFlag: true,
    unlocked: false,
  },
] as const satisfies readonly NpcDefinition[];

export function getNpcById(id: number): NpcDefinition | undefined {
  return NPCS.find((n) => n.id === id);
}
